POST http://localhost:3100/api/auth/login
Content-Type: application/json

{
  "username": "zhangsan",
  "password": "111111"
}
###

POST http://localhost:3100/api/user/register
Content-Type: application/json

{
  "username": "zhangsan",
  "password": "111111",
  "nickname": "张三"
}
###
PATCH http://localhost:3100/api/survey/1980554264178593802
Content-Type: application/json

{
  "desc": "测试修改描述信息1111"
}
###
DELETE http://localhost:3100/api/survey/1980554268649721867
Accept: application/json

###
GET http://localhost:3100/api/survey/1980554268649721867
Accept: application/json

###
GET http://localhost:3100/api/survey?page=1&pageSize=4&keyword=11
Accept: application/json

###
POST http://localhost:3100/api/survey
Content-Type: application/json

{
}

###



